name=Si114xSensor
version=0.0.0
author=mumanchu
maintainer=mumanchu <info@muman.ch>
sentence=Library for Si1145/6/7 ALS, IR and Proximity Sensor + UV Index
paragraph=
category=Sensors
includes=Si114xSensor.h
url=https://github.com/mumanchu/Si114xSensor
architectures=*
